Repository env0/terratag, pull requests merged in 2022-04, with the labels that each got.

#114 chore: upgrade Go to 1.16
  .github/workflows/ci.yml
  .github/workflows/release.yml
  README.md
  go.mod
  go.sum
Labels: pending final review

#116 Chore: build instructions in README.md don't work
  README.md
Labels: documentation, pending final review

#119 Fix: tests pass even if tests folders do not exist
  terratag_test.go
Labels: pending final review

#118 Fix: running more than once with -rename=false will corrupt hcl file
  convert/convert.go
  convert/terratag_locals.go
  main.go
  test/fixture/terraform_15_1.0/git_issue_88__corrupt_hcl_file/expected/main.terratag.tf
  test/fixture/terraform_15_1.0/git_issue_88__corrupt_hcl_file/expected/main.tf.bak
  test/fixture/terraform_15_1.0/git_issue_88__corrupt_hcl_file/input/main.tf
Labels: pending final review

#122 Feat: update to go 1.18
  .github/workflows/ci.yml
  .github/workflows/release.yml
  README.md
  go.mod
  go.sum
Labels: ready to merge

#123 Fix: passing a non-JSON string to terratag should not panic
  main.go
Labels: ready to merge

#124 Fix: terratag panics if module not found
  terraform/terraform.go
Labels: pending final review

#125 Feat : Support go module import
  cli/counters.go
  cli/terratag.go
  main.go
  terratag_test.go
Labels: pending final review
